# Generated by Django 2.0.7 on 2018-07-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256)),
                ('key', models.CharField(max_length=256)),
                ('create_time', models.CharField(max_length=14)),
                ('binding', models.TextField(max_length=65535)),
            ],
        ),
    ]
