# Generated by Django 2.0.7 on 2018-07-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='binding',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
    ]
